
CREATE TABLE  IF NOT EXISTS requests
(
    ID SERIAL PRIMARY KEY NOT NULL,
    TITLE VARCHAR(255) NOT NULL,
    TEXT VARCHAR(255) NOT NULL,
    STATUS VARCHAR(255) NOT NULL,
    REG_DATE TIMESTAMP NOT NULL,
    USER_ID   INTEGER references users (id) on delete set null

);