

CREATE TABLE IF NOT EXISTS users
(
    USER_ID          SERIAL PRIMARY KEY NOT NULL,
    EMAIL      VARCHAR(255) UNIQUE,
    ROLE        VARCHAR(255) NOT NULL,
    FIRST_NAME VARCHAR(255) NOT NULL,
    LAST_NAME   VARCHAR(255) NOT NULL,
    PHONE   VARCHAR(255) NOT NULL
);